### ISSUE TITLE
Progress bar on load

### ISSUE THREAD

**Issue by lsabi** [rethinkdb/rethinkdb-admin#3]
The issue has been already raised in the original Rethinkdb's repo, so I'm linking it below

[https://github.com/rethinkdb/rethinkdb/issues/1651](https://github.com/rethinkdb/rethinkdb/issues/1651)

**Description**
Basically, there are 2MB of assets to be downloaded, so the loading of pages was quite slow back in 2013. Now connections are faster, though web apps have evolved and user expectations are much higher nowadays.

**Solution**
Reduce the number of assets to the bare minimum and make the UI more user friendly thanks to a progress bar (or circle). Possibly remove some useless assets or delay download until needed.

**Comment by atassis** [comment]
Asking too much for a project barely supported by someone=)

**Comment by lsabi** [comment]
I was just porting the issue from the main repo to the (now) separate repo for the UI.

I completely understand your point, but in my opinion, it's a necessary though not urgent, feature. I remember quitting learning react because it's a real pain in the ass, so I can't help here. Nevertheless I would keep it open for when either we manage to rebuild a strong community or I manage to understand react.

Maybe we could add new labels like "high-priority", "medium-priority" and "low-priority" and assign to this the latter. What do you think?

**Comment by srh** [comment]
I think the idea of making it lighter weight is pretty reasonable.  Especially since it's non-commercial, we don't need all the visual bling.

Probably just by avoiding custom fonts:

https://github.com/rethinkdb/rethinkdb/tree/v2.4.x/admin/static/fonts

we could drop the size quite a bit.

**Comment by atassis** [comment]
@srh the main concern is that we need to put an effort into features first. No need to add any big weighted libraries for no good reason, but still features first. I still need people to help me with the repo, at least someone from the core team to help me set task descriptions more precisely.

**Comment by atassis** [comment]
@lsabi we won't add anything big weighted to the project without any reason, I am trying to fix big sized bundles by myself in my own projects/job

**Comment by lsabi** [comment]
@atassis I got lost. Are you referring to adding new libraries for providing a feedback to the user, or in general?

This is not an urgent feature, so it can be left aside for better times. I was just porting some issues from the main repo to related repo.

More in general, removing libraries that affect performances should be a long term goal, that continues through time. But again, this is not a top priority.

**Comment by atassis** [comment]
@lsabi how did you manage to my misunderstand in such a way?:)
Shorter saying: I need help; I am not adding big sized things without a reason.

**Comment by lsabi** [comment]
I only ported the issue and said that it can be done in the future with no hurry. I perfectly understand your point, since I'm doing the same for the python driver.

I would leave the issue open and whoever has time to do collaborate, is free to do so.

**Comment by atassis** [comment]
@lsabi thinking of issue being not the best place to search for collaborators:)
We truly need some announcement of needing the help in developing this.
It might reduce the db's codebase as well, though less and less people are using it

**Comment by atassis** [comment]
So in current state an admin frontend downloads less than 400kb in total in less then half a second (runs locally). Considering this as a successful work. And yes, keeping in mind that if we increase the bundle size for some reason- i'll add lazy loading for some pages (data explorer page as first to be lazy loaded)
